System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "typescript",
  typescriptOptions: {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "build.js": [
      "app/bootstrap.ts",
      "npm:@angular/common@2.0.0-rc.1/index.js",
      "npm:@angular/common@2.0.0-rc.1/src/location.js",
      "npm:@angular/common@2.0.0-rc.1/src/location/location.js",
      "npm:@angular/common@2.0.0-rc.1/src/location/location_strategy.js",
      "npm:@angular/core@2.0.0-rc.1/index.js",
      "npm:@angular/core@2.0.0-rc.1/private_export.js",
      "npm:@angular/core@2.0.0-rc.1/src/console.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/decorators.js",
      "npm:@angular/core@2.0.0-rc.1/src/util/decorators.js",
      "npm:@angular/core@2.0.0-rc.1/src/facade/lang.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/metadata.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/provider_util.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/provider.js",
      "npm:@angular/core@2.0.0-rc.1/src/facade/exceptions.js",
      "npm:@angular/core@2.0.0-rc.1/src/facade/exception_handler.js",
      "npm:@angular/core@2.0.0-rc.1/src/facade/collection.js",
      "npm:@angular/core@2.0.0-rc.1/src/facade/base_wrapped_exception.js",
      "npm:@angular/core@2.0.0-rc.1/src/debug/debug_renderer.js",
      "npm:@angular/core@2.0.0-rc.1/src/debug/debug_node.js",
      "npm:@angular/core@2.0.0-rc.1/src/reflection/reflection_capabilities.js",
      "npm:@angular/core@2.0.0-rc.1/src/profile/wtf_init.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/template_ref.js",
      "npm:@angular/core@2.0.0-rc.1/src/render/api.js",
      "npm:@angular/core@2.0.0-rc.1/src/change_detection/change_detection_util.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/debug_context.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/view_type.js",
      "npm:@angular/core@2.0.0-rc.1/src/metadata/view.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:process@0.11.3.js",
      "npm:process@0.11.3/browser.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/view_utils.js",
      "npm:@angular/core@2.0.0-rc.1/src/application_tokens.js",
      "npm:@angular/core@2.0.0-rc.1/src/di.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/opaque_token.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/reflective_exceptions.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/reflective_key.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/forward_ref.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/reflective_provider.js",
      "npm:@angular/core@2.0.0-rc.1/src/reflection/reflection.js",
      "npm:@angular/core@2.0.0-rc.1/src/reflection/reflector.js",
      "npm:@angular/core@2.0.0-rc.1/src/reflection/reflector_reader.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/reflective_injector.js",
      "npm:@angular/core@2.0.0-rc.1/src/di/injector.js",
      "npm:@angular/core@2.0.0-rc.1/src/change_detection/change_detection.js",
      "npm:@angular/core@2.0.0-rc.1/src/change_detection/change_detector_ref.js",
      "npm:@angular/core@2.0.0-rc.1/src/change_detection/constants.js",
      "npm:@angular/core@2.0.0-rc.1/src/change_detection/differs/default_keyvalue_differ.js",
      "npm:@angular/core@2.0.0-rc.1/src/change_detection/differs/keyvalue_differs.js",
      "npm:@angular/core@2.0.0-rc.1/src/change_detection/differs/default_iterable_differ.js",
      "npm:@angular/core@2.0.0-rc.1/src/change_detection/differs/iterable_differs.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/exceptions.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/element.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/view_container_ref.js",
      "npm:@angular/core@2.0.0-rc.1/src/profile/profile.js",
      "npm:@angular/core@2.0.0-rc.1/src/profile/wtf_impl.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/element_ref.js",
      "npm:@angular/core@2.0.0-rc.1/src/security.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/view.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/element_injector.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/view_ref.js",
      "npm:@angular/core@2.0.0-rc.1/src/facade/async.js",
      "npm:rxjs@5.0.0-beta.6/Observable.js",
      "npm:rxjs@5.0.0-beta.6/util/toSubscriber.js",
      "npm:rxjs@5.0.0-beta.6/symbol/rxSubscriber.js",
      "npm:rxjs@5.0.0-beta.6/util/root.js",
      "npm:rxjs@5.0.0-beta.6/Subscriber.js",
      "npm:rxjs@5.0.0-beta.6/Observer.js",
      "npm:rxjs@5.0.0-beta.6/Subscription.js",
      "npm:rxjs@5.0.0-beta.6/util/UnsubscriptionError.js",
      "npm:rxjs@5.0.0-beta.6/util/errorObject.js",
      "npm:rxjs@5.0.0-beta.6/util/tryCatch.js",
      "npm:rxjs@5.0.0-beta.6/util/isFunction.js",
      "npm:rxjs@5.0.0-beta.6/util/isObject.js",
      "npm:rxjs@5.0.0-beta.6/util/isArray.js",
      "npm:rxjs@5.0.0-beta.6/symbol/observable.js",
      "npm:rxjs@5.0.0-beta.6/operator/toPromise.js",
      "npm:rxjs@5.0.0-beta.6/observable/PromiseObservable.js",
      "npm:rxjs@5.0.0-beta.6/Subject.js",
      "npm:rxjs@5.0.0-beta.6/util/ObjectUnsubscribedError.js",
      "npm:rxjs@5.0.0-beta.6/util/throwError.js",
      "npm:rxjs@5.0.0-beta.6/SubjectSubscription.js",
      "npm:@angular/core@2.0.0-rc.1/src/facade/promise.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/component_resolver.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/component_factory.js",
      "npm:@angular/core@2.0.0-rc.1/src/metadata/lifecycle_hooks.js",
      "npm:@angular/core@2.0.0-rc.1/src/application_common_providers.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/dynamic_component_loader.js",
      "npm:@angular/core@2.0.0-rc.1/src/application_ref.js",
      "npm:@angular/core@2.0.0-rc.1/src/testability/testability.js",
      "npm:@angular/core@2.0.0-rc.1/src/zone/ng_zone.js",
      "npm:@angular/core@2.0.0-rc.1/src/zone/ng_zone_impl.js",
      "npm:@angular/core@2.0.0-rc.1/src/platform_common_providers.js",
      "npm:@angular/core@2.0.0-rc.1/src/platform_directives_and_pipes.js",
      "npm:@angular/core@2.0.0-rc.1/src/change_detection.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker.js",
      "npm:@angular/core@2.0.0-rc.1/src/linker/query_list.js",
      "npm:@angular/core@2.0.0-rc.1/src/render.js",
      "npm:@angular/core@2.0.0-rc.1/src/zone.js",
      "npm:@angular/core@2.0.0-rc.1/src/util.js",
      "npm:@angular/core@2.0.0-rc.1/src/metadata.js",
      "npm:@angular/core@2.0.0-rc.1/src/metadata/directives.js",
      "npm:@angular/core@2.0.0-rc.1/src/metadata/di.js",
      "npm:@angular/common@2.0.0-rc.1/src/facade/async.js",
      "npm:@angular/common@2.0.0-rc.1/src/facade/promise.js",
      "npm:@angular/common@2.0.0-rc.1/src/facade/lang.js",
      "npm:@angular/common@2.0.0-rc.1/src/location/path_location_strategy.js",
      "npm:@angular/common@2.0.0-rc.1/src/location/platform_location.js",
      "npm:@angular/common@2.0.0-rc.1/src/facade/exceptions.js",
      "npm:@angular/common@2.0.0-rc.1/src/facade/exception_handler.js",
      "npm:@angular/common@2.0.0-rc.1/src/facade/collection.js",
      "npm:@angular/common@2.0.0-rc.1/src/facade/base_wrapped_exception.js",
      "npm:@angular/common@2.0.0-rc.1/src/location/hash_location_strategy.js",
      "npm:@angular/common@2.0.0-rc.1/src/common_directives.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives/core_directives.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives/ng_plural.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives/ng_switch.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives/ng_style.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives/ng_template_outlet.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives/ng_if.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives/ng_for.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives/ng_class.js",
      "npm:@angular/common@2.0.0-rc.1/src/directives/observable_list_diff.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/radio_control_value_accessor.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/ng_control.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/abstract_control_directive.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/control_value_accessor.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/form_builder.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/model.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/validators.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/validators.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/select_control_value_accessor.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/ng_control_status.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/number_value_accessor.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/checkbox_value_accessor.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/default_value_accessor.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/ng_form.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/shared.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/normalize_validator.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/control_container.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/ng_form_model.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/ng_control_group.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/ng_model.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/ng_form_control.js",
      "npm:@angular/common@2.0.0-rc.1/src/forms/directives/ng_control_name.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/common_pipes.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/i18n_select_pipe.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/invalid_pipe_argument_exception.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/i18n_plural_pipe.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/replace_pipe.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/number_pipe.js",
      "npm:@angular/common@2.0.0-rc.1/src/facade/intl.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/date_pipe.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/slice_pipe.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/json_pipe.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/lowercase_pipe.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/uppercase_pipe.js",
      "npm:@angular/common@2.0.0-rc.1/src/pipes/async_pipe.js",
      "npm:@angular/router@2.0.0-rc.1.js",
      "npm:@angular/router@2.0.0-rc.1/index.js",
      "npm:@angular/router@2.0.0-rc.1/src/directives/router_link.js",
      "npm:@angular/router@2.0.0-rc.1/src/facade/async.js",
      "npm:@angular/router@2.0.0-rc.1/src/facade/promise.js",
      "npm:@angular/router@2.0.0-rc.1/src/facade/lang.js",
      "npm:@angular/router@2.0.0-rc.1/src/segments.js",
      "npm:@angular/router@2.0.0-rc.1/src/facade/collection.js",
      "npm:@angular/router@2.0.0-rc.1/src/router.js",
      "npm:@angular/router@2.0.0-rc.1/src/constants.js",
      "npm:@angular/router@2.0.0-rc.1/src/lifecycle_reflector.js",
      "npm:@angular/router@2.0.0-rc.1/src/link.js",
      "npm:@angular/router@2.0.0-rc.1/src/facade/exceptions.js",
      "npm:@angular/router@2.0.0-rc.1/src/facade/exception_handler.js",
      "npm:@angular/router@2.0.0-rc.1/src/facade/base_wrapped_exception.js",
      "npm:@angular/router@2.0.0-rc.1/src/recognize.js",
      "npm:@angular/router@2.0.0-rc.1/src/metadata/metadata.js",
      "npm:@angular/router@2.0.0-rc.1/src/directives/router_outlet.js",
      "npm:@angular/router@2.0.0-rc.1/src/router_providers.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/index.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/platform_browser.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/platform_browser_static.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/browser/location/browser_platform_location.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/dom_adapter.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/facade/lang.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/debug/ng_probe.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/dom_renderer.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/util.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/dom_tokens.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/events/event_manager.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/facade/collection.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/facade/exceptions.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/facade/exception_handler.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/facade/base_wrapped_exception.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/shared_styles_host.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/animate/animation_builder.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/animate/browser_details.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/facade/math.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/animate/css_animation_builder.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/animate/animation.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/animate/css_animation_options.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/core_private.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/browser_common.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/debug/by.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/browser/tools/tools.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/browser/tools/common_tools.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/facade/browser.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/browser/title.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/events/hammer_gestures.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/events/hammer_common.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/events/dom_events.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/dom/events/key_events.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/browser/testability.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/browser/browser_adapter.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/browser/generic_browser_adapter.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/security/dom_sanitization_service.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/security/style_sanitizer.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/src/security/url_sanitizer.js",
      "npm:@angular/platform-browser@2.0.0-rc.1/private_export.js",
      "npm:@angular/router@2.0.0-rc.1/src/router_providers_common.js",
      "npm:@angular/router@2.0.0-rc.1/src/router_url_serializer.js",
      "npm:@angular/router@2.0.0-rc.1/src/metadata/decorators.js",
      "npm:@angular/router@2.0.0-rc.1/src/core_private.js",
      "app/appComponent.ts",
      "app/services/signalrService.ts",
      "npm:moment@2.13.0.js",
      "npm:moment@2.13.0/moment.js",
      "app/services/userInfoService.ts",
      "npm:rxjs@5.0.0-beta.6/add/operator/map.js",
      "npm:rxjs@5.0.0-beta.6/operator/map.js",
      "npm:rxjs@5.0.0-beta.6/Rx.js",
      "npm:rxjs@5.0.0-beta.6/symbol/iterator.js",
      "npm:rxjs@5.0.0-beta.6/scheduler/queue.js",
      "npm:rxjs@5.0.0-beta.6/scheduler/QueueScheduler.js",
      "npm:rxjs@5.0.0-beta.6/scheduler/FutureAction.js",
      "npm:rxjs@5.0.0-beta.6/scheduler/QueueAction.js",
      "npm:rxjs@5.0.0-beta.6/scheduler/async.js",
      "npm:rxjs@5.0.0-beta.6/scheduler/AsyncScheduler.js",
      "npm:rxjs@5.0.0-beta.6/scheduler/asap.js",
      "npm:rxjs@5.0.0-beta.6/scheduler/AsapScheduler.js",
      "npm:rxjs@5.0.0-beta.6/scheduler/AsapAction.js",
      "npm:rxjs@5.0.0-beta.6/util/Immediate.js",
      "npm:rxjs@5.0.0-beta.6/util/ArgumentOutOfRangeError.js",
      "npm:rxjs@5.0.0-beta.6/util/EmptyError.js",
      "npm:rxjs@5.0.0-beta.6/Notification.js",
      "npm:rxjs@5.0.0-beta.6/observable/ConnectableObservable.js",
      "npm:rxjs@5.0.0-beta.6/BehaviorSubject.js",
      "npm:rxjs@5.0.0-beta.6/ReplaySubject.js",
      "npm:rxjs@5.0.0-beta.6/operator/observeOn.js",
      "npm:rxjs@5.0.0-beta.6/AsyncSubject.js",
      "npm:rxjs@5.0.0-beta.6/Operator.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/zipAll.js",
      "npm:rxjs@5.0.0-beta.6/operator/zipAll.js",
      "npm:rxjs@5.0.0-beta.6/operator/zip.js",
      "npm:rxjs@5.0.0-beta.6/util/subscribeToResult.js",
      "npm:rxjs@5.0.0-beta.6/InnerSubscriber.js",
      "npm:rxjs@5.0.0-beta.6/util/isPromise.js",
      "npm:rxjs@5.0.0-beta.6/OuterSubscriber.js",
      "npm:rxjs@5.0.0-beta.6/observable/ArrayObservable.js",
      "npm:rxjs@5.0.0-beta.6/util/isScheduler.js",
      "npm:rxjs@5.0.0-beta.6/observable/EmptyObservable.js",
      "npm:rxjs@5.0.0-beta.6/observable/ScalarObservable.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/zip.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/withLatestFrom.js",
      "npm:rxjs@5.0.0-beta.6/operator/withLatestFrom.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/windowWhen.js",
      "npm:rxjs@5.0.0-beta.6/operator/windowWhen.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/windowToggle.js",
      "npm:rxjs@5.0.0-beta.6/operator/windowToggle.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/windowTime.js",
      "npm:rxjs@5.0.0-beta.6/operator/windowTime.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/windowCount.js",
      "npm:rxjs@5.0.0-beta.6/operator/windowCount.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/window.js",
      "npm:rxjs@5.0.0-beta.6/operator/window.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/toPromise.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/toArray.js",
      "npm:rxjs@5.0.0-beta.6/operator/toArray.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/timeoutWith.js",
      "npm:rxjs@5.0.0-beta.6/operator/timeoutWith.js",
      "npm:rxjs@5.0.0-beta.6/util/isDate.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/timeout.js",
      "npm:rxjs@5.0.0-beta.6/operator/timeout.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/throttleTime.js",
      "npm:rxjs@5.0.0-beta.6/operator/throttleTime.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/throttle.js",
      "npm:rxjs@5.0.0-beta.6/operator/throttle.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/takeWhile.js",
      "npm:rxjs@5.0.0-beta.6/operator/takeWhile.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/takeUntil.js",
      "npm:rxjs@5.0.0-beta.6/operator/takeUntil.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/takeLast.js",
      "npm:rxjs@5.0.0-beta.6/operator/takeLast.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/take.js",
      "npm:rxjs@5.0.0-beta.6/operator/take.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/switchMapTo.js",
      "npm:rxjs@5.0.0-beta.6/operator/switchMapTo.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/switchMap.js",
      "npm:rxjs@5.0.0-beta.6/operator/switchMap.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/switch.js",
      "npm:rxjs@5.0.0-beta.6/operator/switch.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/subscribeOn.js",
      "npm:rxjs@5.0.0-beta.6/operator/subscribeOn.js",
      "npm:rxjs@5.0.0-beta.6/observable/SubscribeOnObservable.js",
      "npm:rxjs@5.0.0-beta.6/util/isNumeric.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/startWith.js",
      "npm:rxjs@5.0.0-beta.6/operator/startWith.js",
      "npm:rxjs@5.0.0-beta.6/operator/concat.js",
      "npm:rxjs@5.0.0-beta.6/operator/mergeAll.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/skipWhile.js",
      "npm:rxjs@5.0.0-beta.6/operator/skipWhile.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/skipUntil.js",
      "npm:rxjs@5.0.0-beta.6/operator/skipUntil.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/skip.js",
      "npm:rxjs@5.0.0-beta.6/operator/skip.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/single.js",
      "npm:rxjs@5.0.0-beta.6/operator/single.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/share.js",
      "npm:rxjs@5.0.0-beta.6/operator/share.js",
      "npm:rxjs@5.0.0-beta.6/operator/multicast.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/scan.js",
      "npm:rxjs@5.0.0-beta.6/operator/scan.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/sampleTime.js",
      "npm:rxjs@5.0.0-beta.6/operator/sampleTime.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/sample.js",
      "npm:rxjs@5.0.0-beta.6/operator/sample.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/retryWhen.js",
      "npm:rxjs@5.0.0-beta.6/operator/retryWhen.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/retry.js",
      "npm:rxjs@5.0.0-beta.6/operator/retry.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/repeat.js",
      "npm:rxjs@5.0.0-beta.6/operator/repeat.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/reduce.js",
      "npm:rxjs@5.0.0-beta.6/operator/reduce.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/race.js",
      "npm:rxjs@5.0.0-beta.6/operator/race.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/publishLast.js",
      "npm:rxjs@5.0.0-beta.6/operator/publishLast.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/publishReplay.js",
      "npm:rxjs@5.0.0-beta.6/operator/publishReplay.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/publishBehavior.js",
      "npm:rxjs@5.0.0-beta.6/operator/publishBehavior.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/publish.js",
      "npm:rxjs@5.0.0-beta.6/operator/publish.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/pluck.js",
      "npm:rxjs@5.0.0-beta.6/operator/pluck.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/partition.js",
      "npm:rxjs@5.0.0-beta.6/operator/partition.js",
      "npm:rxjs@5.0.0-beta.6/operator/filter.js",
      "npm:rxjs@5.0.0-beta.6/util/not.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/observeOn.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/multicast.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/mergeMapTo.js",
      "npm:rxjs@5.0.0-beta.6/operator/mergeMapTo.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/mergeMap.js",
      "npm:rxjs@5.0.0-beta.6/operator/mergeMap.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/mergeAll.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/merge.js",
      "npm:rxjs@5.0.0-beta.6/operator/merge.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/materialize.js",
      "npm:rxjs@5.0.0-beta.6/operator/materialize.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/mapTo.js",
      "npm:rxjs@5.0.0-beta.6/operator/mapTo.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/every.js",
      "npm:rxjs@5.0.0-beta.6/operator/every.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/let.js",
      "npm:rxjs@5.0.0-beta.6/operator/let.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/last.js",
      "npm:rxjs@5.0.0-beta.6/operator/last.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/auditTime.js",
      "npm:rxjs@5.0.0-beta.6/operator/auditTime.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/audit.js",
      "npm:rxjs@5.0.0-beta.6/operator/audit.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/ignoreElements.js",
      "npm:rxjs@5.0.0-beta.6/operator/ignoreElements.js",
      "npm:rxjs@5.0.0-beta.6/util/noop.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/groupBy.js",
      "npm:rxjs@5.0.0-beta.6/operator/groupBy.js",
      "npm:rxjs@5.0.0-beta.6/util/FastMap.js",
      "npm:rxjs@5.0.0-beta.6/util/Map.js",
      "npm:rxjs@5.0.0-beta.6/util/MapPolyfill.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/first.js",
      "npm:rxjs@5.0.0-beta.6/operator/first.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/finally.js",
      "npm:rxjs@5.0.0-beta.6/operator/finally.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/filter.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/expand.js",
      "npm:rxjs@5.0.0-beta.6/operator/expand.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/do.js",
      "npm:rxjs@5.0.0-beta.6/operator/do.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/distinctUntilChanged.js",
      "npm:rxjs@5.0.0-beta.6/operator/distinctUntilChanged.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/delayWhen.js",
      "npm:rxjs@5.0.0-beta.6/operator/delayWhen.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/delay.js",
      "npm:rxjs@5.0.0-beta.6/operator/delay.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/defaultIfEmpty.js",
      "npm:rxjs@5.0.0-beta.6/operator/defaultIfEmpty.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/debounceTime.js",
      "npm:rxjs@5.0.0-beta.6/operator/debounceTime.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/debounce.js",
      "npm:rxjs@5.0.0-beta.6/operator/debounce.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/dematerialize.js",
      "npm:rxjs@5.0.0-beta.6/operator/dematerialize.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/count.js",
      "npm:rxjs@5.0.0-beta.6/operator/count.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/concatMapTo.js",
      "npm:rxjs@5.0.0-beta.6/operator/concatMapTo.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/concatMap.js",
      "npm:rxjs@5.0.0-beta.6/operator/concatMap.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/concatAll.js",
      "npm:rxjs@5.0.0-beta.6/operator/concatAll.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/concat.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/combineLatest.js",
      "npm:rxjs@5.0.0-beta.6/operator/combineLatest.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/combineAll.js",
      "npm:rxjs@5.0.0-beta.6/operator/combineAll.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/catch.js",
      "npm:rxjs@5.0.0-beta.6/operator/catch.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/cache.js",
      "npm:rxjs@5.0.0-beta.6/operator/cache.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/bufferWhen.js",
      "npm:rxjs@5.0.0-beta.6/operator/bufferWhen.js",
      "github:jspm/nodelibs-buffer@0.1.0.js",
      "github:jspm/nodelibs-buffer@0.1.0/index.js",
      "npm:buffer@3.6.0.js",
      "npm:buffer@3.6.0/index.js",
      "npm:isarray@1.0.0.js",
      "npm:isarray@1.0.0/index.js",
      "npm:ieee754@1.1.6.js",
      "npm:ieee754@1.1.6/index.js",
      "npm:base64-js@0.0.8.js",
      "npm:base64-js@0.0.8/lib/b64.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/bufferToggle.js",
      "npm:rxjs@5.0.0-beta.6/operator/bufferToggle.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/bufferTime.js",
      "npm:rxjs@5.0.0-beta.6/operator/bufferTime.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/bufferCount.js",
      "npm:rxjs@5.0.0-beta.6/operator/bufferCount.js",
      "npm:rxjs@5.0.0-beta.6/add/operator/buffer.js",
      "npm:rxjs@5.0.0-beta.6/operator/buffer.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/zip.js",
      "npm:rxjs@5.0.0-beta.6/observable/zip.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/timer.js",
      "npm:rxjs@5.0.0-beta.6/observable/timer.js",
      "npm:rxjs@5.0.0-beta.6/observable/TimerObservable.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/throw.js",
      "npm:rxjs@5.0.0-beta.6/observable/throw.js",
      "npm:rxjs@5.0.0-beta.6/observable/ErrorObservable.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/range.js",
      "npm:rxjs@5.0.0-beta.6/observable/range.js",
      "npm:rxjs@5.0.0-beta.6/observable/RangeObservable.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/of.js",
      "npm:rxjs@5.0.0-beta.6/observable/of.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/never.js",
      "npm:rxjs@5.0.0-beta.6/observable/never.js",
      "npm:rxjs@5.0.0-beta.6/observable/NeverObservable.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/race.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/merge.js",
      "npm:rxjs@5.0.0-beta.6/observable/merge.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/interval.js",
      "npm:rxjs@5.0.0-beta.6/observable/interval.js",
      "npm:rxjs@5.0.0-beta.6/observable/IntervalObservable.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/fromPromise.js",
      "npm:rxjs@5.0.0-beta.6/observable/fromPromise.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/fromEventPattern.js",
      "npm:rxjs@5.0.0-beta.6/observable/fromEventPattern.js",
      "npm:rxjs@5.0.0-beta.6/observable/FromEventPatternObservable.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/fromEvent.js",
      "npm:rxjs@5.0.0-beta.6/observable/fromEvent.js",
      "npm:rxjs@5.0.0-beta.6/observable/FromEventObservable.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/from.js",
      "npm:rxjs@5.0.0-beta.6/observable/from.js",
      "npm:rxjs@5.0.0-beta.6/observable/FromObservable.js",
      "npm:rxjs@5.0.0-beta.6/observable/ArrayLikeObservable.js",
      "npm:rxjs@5.0.0-beta.6/observable/IteratorObservable.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/forkJoin.js",
      "npm:rxjs@5.0.0-beta.6/observable/forkJoin.js",
      "npm:rxjs@5.0.0-beta.6/observable/ForkJoinObservable.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/empty.js",
      "npm:rxjs@5.0.0-beta.6/observable/empty.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/defer.js",
      "npm:rxjs@5.0.0-beta.6/observable/defer.js",
      "npm:rxjs@5.0.0-beta.6/observable/DeferObservable.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/concat.js",
      "npm:rxjs@5.0.0-beta.6/observable/concat.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/combineLatest.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/bindNodeCallback.js",
      "npm:rxjs@5.0.0-beta.6/observable/bindNodeCallback.js",
      "npm:rxjs@5.0.0-beta.6/observable/BoundNodeCallbackObservable.js",
      "npm:rxjs@5.0.0-beta.6/add/observable/bindCallback.js",
      "npm:rxjs@5.0.0-beta.6/observable/bindCallback.js",
      "npm:rxjs@5.0.0-beta.6/observable/BoundCallbackObservable.js",
      "npm:@angular/http@2.0.0-rc.1/index.js",
      "npm:@angular/http@2.0.0-rc.1/http.js",
      "npm:@angular/http@2.0.0-rc.1/src/url_search_params.js",
      "npm:@angular/http@2.0.0-rc.1/src/facade/collection.js",
      "npm:@angular/http@2.0.0-rc.1/src/facade/lang.js",
      "npm:@angular/http@2.0.0-rc.1/src/enums.js",
      "npm:@angular/http@2.0.0-rc.1/src/headers.js",
      "npm:@angular/http@2.0.0-rc.1/src/facade/exceptions.js",
      "npm:@angular/http@2.0.0-rc.1/src/facade/exception_handler.js",
      "npm:@angular/http@2.0.0-rc.1/src/facade/base_wrapped_exception.js",
      "npm:@angular/http@2.0.0-rc.1/src/interfaces.js",
      "npm:@angular/http@2.0.0-rc.1/src/static_response.js",
      "npm:@angular/http@2.0.0-rc.1/src/http_utils.js",
      "npm:@angular/http@2.0.0-rc.1/src/static_request.js",
      "npm:@angular/http@2.0.0-rc.1/src/base_response_options.js",
      "npm:@angular/http@2.0.0-rc.1/src/base_request_options.js",
      "npm:@angular/http@2.0.0-rc.1/src/backends/browser_jsonp.js",
      "npm:@angular/http@2.0.0-rc.1/src/backends/browser_xhr.js",
      "npm:@angular/http@2.0.0-rc.1/src/backends/jsonp_backend.js",
      "npm:@angular/http@2.0.0-rc.1/src/backends/xhr_backend.js",
      "npm:@angular/http@2.0.0-rc.1/src/http.js",
      "app/services/audioZoneService.ts",
      "app/services/queueService.ts",
      "app/services/albumService.ts",
      "app/services/artistService.ts",
      "app/services/searchService.ts",
      "app/search/searchResultsComponent.ts",
      "app/nowPlaying/zoneSelectorComponent.ts",
      "npm:ng2-bootstrap@1.0.16/ng2-bootstrap.js",
      "npm:ng2-bootstrap@1.0.16/components/ng2-bootstrap-config.js",
      "npm:ng2-bootstrap@1.0.16/components/common.js",
      "npm:ng2-bootstrap@1.0.16/components/position.js",
      "npm:ng2-bootstrap@1.0.16/components/typeahead.js",
      "npm:ng2-bootstrap@1.0.16/components/typeahead/typeahead-options.class.js",
      "npm:ng2-bootstrap@1.0.16/components/typeahead/typeahead-container.component.js",
      "npm:ng2-bootstrap@1.0.16/components/typeahead/typeahead-utils.js",
      "npm:ng2-bootstrap@1.0.16/components/typeahead/latin-map.js",
      "npm:ng2-bootstrap@1.0.16/components/typeahead/typeahead.directive.js",
      "npm:ng2-bootstrap@1.0.16/components/tooltip.js",
      "npm:ng2-bootstrap@1.0.16/components/tooltip/tooltip-container.component.js",
      "npm:ng2-bootstrap@1.0.16/components/tooltip/tooltip-options.class.js",
      "npm:ng2-bootstrap@1.0.16/components/tooltip/tooltip.directive.js",
      "npm:ng2-bootstrap@1.0.16/components/timepicker.js",
      "npm:ng2-bootstrap@1.0.16/components/timepicker/timepicker.component.js",
      "npm:ng2-bootstrap@1.0.16/components/tabs.js",
      "npm:ng2-bootstrap@1.0.16/components/tabs/tab-heading.directive.js",
      "npm:ng2-bootstrap@1.0.16/components/tabs/tab.directive.js",
      "npm:ng2-bootstrap@1.0.16/components/tabs/tabset.component.js",
      "npm:ng2-bootstrap@1.0.16/components/rating.js",
      "npm:ng2-bootstrap@1.0.16/components/rating/rating.component.js",
      "npm:ng2-bootstrap@1.0.16/components/progressbar.js",
      "npm:ng2-bootstrap@1.0.16/components/progressbar/progressbar.component.js",
      "npm:ng2-bootstrap@1.0.16/components/progressbar/bar.component.js",
      "npm:ng2-bootstrap@1.0.16/components/progressbar/progress.directive.js",
      "npm:ng2-bootstrap@1.0.16/components/pagination.js",
      "npm:ng2-bootstrap@1.0.16/components/pagination/pager.component.js",
      "npm:ng2-bootstrap@1.0.16/components/pagination/pagination.component.js",
      "npm:ng2-bootstrap@1.0.16/components/dropdown.js",
      "npm:ng2-bootstrap@1.0.16/components/dropdown/dropdown-toggle.directive.js",
      "npm:ng2-bootstrap@1.0.16/components/dropdown/dropdown.directive.js",
      "npm:ng2-bootstrap@1.0.16/components/dropdown/dropdown.service.js",
      "npm:ng2-bootstrap@1.0.16/components/dropdown/dropdown-menu.directive.js",
      "npm:ng2-bootstrap@1.0.16/components/datepicker.js",
      "npm:ng2-bootstrap@1.0.16/components/datepicker/datepicker.component.js",
      "npm:ng2-bootstrap@1.0.16/components/datepicker/yearpicker.component.js",
      "npm:ng2-bootstrap@1.0.16/components/datepicker/datepicker-inner.component.js",
      "npm:ng2-bootstrap@1.0.16/components/datepicker/date-formatter.js",
      "npm:ng2-bootstrap@1.0.16/components/datepicker/monthpicker.component.js",
      "npm:ng2-bootstrap@1.0.16/components/datepicker/daypicker.component.js",
      "npm:ng2-bootstrap@1.0.16/components/datepicker/datepicker-popup.component.js",
      "npm:ng2-bootstrap@1.0.16/components/collapse.js",
      "npm:ng2-bootstrap@1.0.16/components/collapse/collapse.directive.js",
      "npm:ng2-bootstrap@1.0.16/components/carousel.js",
      "npm:ng2-bootstrap@1.0.16/components/carousel/carousel.component.js",
      "npm:ng2-bootstrap@1.0.16/components/carousel/slide.component.js",
      "npm:ng2-bootstrap@1.0.16/components/buttons.js",
      "npm:ng2-bootstrap@1.0.16/components/buttons/button-radio.directive.js",
      "npm:ng2-bootstrap@1.0.16/components/buttons/button-checkbox.directive.js",
      "npm:ng2-bootstrap@1.0.16/components/alert.js",
      "npm:ng2-bootstrap@1.0.16/components/alert/alert.component.js",
      "npm:ng2-bootstrap@1.0.16/components/accordion.js",
      "npm:ng2-bootstrap@1.0.16/components/accordion/accordion-group.component.js",
      "npm:ng2-bootstrap@1.0.16/components/accordion/accordion.component.js",
      "app/search/breadcrumbsComponent.ts",
      "app/tracks/trackListItemComponent.ts",
      "app/tracks/simpleTrackListItemComponent.ts",
      "app/tracks/queueTrackButtonComponent.ts",
      "app/models/ITrack.d.ts",
      "app/albums/albumListItemComponent.ts",
      "app/models/IAlbum.d.ts",
      "app/artists/artistListItemComponent.ts",
      "app/models/IArtist.d.ts",
      "app/search/searchBarComponent.ts",
      "app/albums/albumDetailsComponent.ts",
      "app/artists/artistDetailsComponent.ts",
      "app/nowPlaying/nowPlayingComponent.ts",
      "app/tracks/QueuedTrackComponent.ts",
      "app/models/IQueuedTrack.d.ts",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/index.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/platform_browser_dynamic.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/core_private.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/src/xhr/xhr_impl.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/src/facade/lang.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/src/facade/promise.js",
      "npm:@angular/compiler@2.0.0-rc.1/index.js",
      "npm:@angular/compiler@2.0.0-rc.1/compiler.js",
      "npm:@angular/compiler@2.0.0-rc.1/private_export.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/output/path_util.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/facade/lang.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/facade/exceptions.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/facade/exception_handler.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/facade/collection.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/facade/base_wrapped_exception.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/selector.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/template_ast.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/compiler.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/expression_parser/lexer.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/expression_parser/parser.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/expression_parser/ast.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/schema/dom_element_schema_registry.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/schema/element_schema_registry.js",
      "npm:@angular/compiler@2.0.0-rc.1/core_private.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/view_compiler.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/config.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/identifiers.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/util.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/compile_metadata.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/url_resolver.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/view_binder.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/lifecycle_binder.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/constants.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/output/output_ast.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/event_binder.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/compile_binding.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/expression_converter.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/compile_method.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/property_binder.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/view_builder.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/util.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/compile_element.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/compile_query.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/compile_view.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_compiler/compile_pipe.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/style_compiler.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/style_url_resolver.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/shadow_css.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/metadata_resolver.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/assertions.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/directive_lifecycle_reflector.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/view_resolver.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/pipe_resolver.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/directive_resolver.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/directive_normalizer.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/template_preparser.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/html_tags.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/html_parser.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/parse_util.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/html_lexer.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/html_ast.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/xhr.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/facade/async.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/facade/promise.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/runtime_compiler.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/output/interpretive_view.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/output/output_interpreter.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/output/ts_emitter.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/output/abstract_emitter.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/output/dart_emitter.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/output/output_jit.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/output/abstract_js_emitter.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/template_parser.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/provider_parser.js",
      "npm:@angular/compiler@2.0.0-rc.1/src/offline_compiler.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/src/xhr/xhr_cache.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/src/facade/exceptions.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/src/facade/exception_handler.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/src/facade/collection.js",
      "npm:@angular/platform-browser-dynamic@2.0.0-rc.1/src/facade/base_wrapped_exception.js"
    ]
  },

  packages: {
    "app": {
      "main": "bootstrap",
      "format": "system",
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "ts"
        }
      }
    },
    "rxjs": {
      "defaultExtension": "js"
    },
    "angular2-in-memory-web-api": {
      "defaultExtension": "js"
    },
    "@angular/common": {
      "main": "index.js",
      "defaultExtension": "js"
    },
    "@angular/compiler": {
      "main": "index.js",
      "defaultExtension": "js"
    },
    "@angular/core": {
      "main": "index.js",
      "defaultExtension": "js"
    },
    "@angular/http": {
      "main": "index.js",
      "defaultExtension": "js"
    },
    "@angular/platform-browser": {
      "main": "index.js",
      "defaultExtension": "js"
    },
    "@angular/platform-browser-dynamic": {
      "main": "index.js",
      "defaultExtension": "js"
    },
    "@angular/router-deprecated": {
      "main": "index.js",
      "defaultExtension": "js"
    },
    "@angular/testing": {
      "main": "index.js",
      "defaultExtension": "js"
    },
    "@angular/upgrade": {
      "main": "index.js",
      "defaultExtension": "js"
    }
  },

  map: {
    "@angular/common": "npm:@angular/common@2.0.0-rc.1",
    "@angular/compiler": "npm:@angular/compiler@2.0.0-rc.1",
    "@angular/core": "npm:@angular/core@2.0.0-rc.1",
    "@angular/http": "npm:@angular/http@2.0.0-rc.1",
    "@angular/platform-browser": "npm:@angular/platform-browser@2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "npm:@angular/platform-browser-dynamic@2.0.0-rc.1",
    "@angular/router": "npm:@angular/router@2.0.0-rc.1",
    "@angular/router-deprecated": "npm:@angular/router-deprecated@2.0.0-rc.1",
    "@angular/upgrade": "npm:@angular/upgrade@2.0.0-rc.1",
    "crypto": "github:jspm/nodelibs-crypto@0.1.0",
    "es6-shim": "github:es-shims/es6-shim@0.35.1",
    "moment": "npm:moment@2.13.0",
    "ng2-bootstrap": "npm:ng2-bootstrap@1.0.16",
    "rxjs": "npm:rxjs@5.0.0-beta.6",
    "ts": "github:frankwallis/plugin-typescript@4.0.16",
    "typescript": "npm:typescript@1.8.10",
    "github:frankwallis/plugin-typescript@4.0.16": {
      "typescript": "npm:typescript@1.8.10"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.4.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-crypto@0.1.0": {
      "crypto-browserify": "npm:crypto-browserify@3.11.0"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-os@0.1.0": {
      "os-browserify": "npm:os-browserify@0.1.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.3"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "npm:@angular/common@2.0.0-rc.1": {
      "@angular/core": "npm:@angular/core@2.0.0-rc.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:@angular/compiler@2.0.0-rc.1": {
      "@angular/core": "npm:@angular/core@2.0.0-rc.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:@angular/core@2.0.0-rc.1": {
      "process": "github:jspm/nodelibs-process@0.1.2",
      "rxjs": "npm:rxjs@5.0.0-beta.6",
      "zone.js": "npm:zone.js@0.6.12"
    },
    "npm:@angular/http@2.0.0-rc.1": {
      "@angular/core": "npm:@angular/core@2.0.0-rc.1",
      "rxjs": "npm:rxjs@5.0.0-beta.6"
    },
    "npm:@angular/platform-browser-dynamic@2.0.0-rc.1": {
      "@angular/common": "npm:@angular/common@2.0.0-rc.1",
      "@angular/compiler": "npm:@angular/compiler@2.0.0-rc.1",
      "@angular/core": "npm:@angular/core@2.0.0-rc.1",
      "@angular/platform-browser": "npm:@angular/platform-browser@2.0.0-rc.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:@angular/platform-browser@2.0.0-rc.1": {
      "@angular/common": "npm:@angular/common@2.0.0-rc.1",
      "@angular/compiler": "npm:@angular/compiler@2.0.0-rc.1",
      "@angular/core": "npm:@angular/core@2.0.0-rc.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:@angular/router-deprecated@2.0.0-rc.1": {
      "@angular/common": "npm:@angular/common@2.0.0-rc.1",
      "@angular/core": "npm:@angular/core@2.0.0-rc.1",
      "@angular/platform-browser": "npm:@angular/platform-browser@2.0.0-rc.1"
    },
    "npm:@angular/router@2.0.0-rc.1": {
      "@angular/common": "npm:@angular/common@2.0.0-rc.1",
      "@angular/core": "npm:@angular/core@2.0.0-rc.1",
      "@angular/platform-browser": "npm:@angular/platform-browser@2.0.0-rc.1"
    },
    "npm:@angular/upgrade@2.0.0-rc.1": {
      "@angular/compiler": "npm:@angular/compiler@2.0.0-rc.1",
      "@angular/core": "npm:@angular/core@2.0.0-rc.1",
      "@angular/platform-browser": "npm:@angular/platform-browser@2.0.0-rc.1"
    },
    "npm:asn1.js@4.6.0": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "bn.js": "npm:bn.js@4.11.3",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:assert@1.4.0": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-shims": "npm:buffer-shims@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "npm:util@0.10.3"
    },
    "npm:bn.js@4.11.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:browserify-aes@1.0.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-xor": "npm:buffer-xor@1.0.3",
      "cipher-base": "npm:cipher-base@1.0.2",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:browserify-cipher@1.0.0": {
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "browserify-des": "npm:browserify-des@1.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0"
    },
    "npm:browserify-des@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "des.js": "npm:des.js@1.0.0",
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:browserify-rsa@4.0.1": {
      "bn.js": "npm:bn.js@4.11.3",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:browserify-sign@4.0.0": {
      "bn.js": "npm:bn.js@4.11.3",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.2.5",
      "inherits": "npm:inherits@2.0.1",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:buffer-shims@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:buffer-xor@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:cipher-base@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:create-ecdh@4.0.0": {
      "bn.js": "npm:bn.js@4.11.3",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.2.5"
    },
    "npm:create-hash@1.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "ripemd160": "npm:ripemd160@1.0.1",
      "sha.js": "npm:sha.js@2.4.5"
    },
    "npm:create-hmac@1.1.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:crypto-browserify@3.11.0": {
      "browserify-cipher": "npm:browserify-cipher@1.0.0",
      "browserify-sign": "npm:browserify-sign@4.0.0",
      "create-ecdh": "npm:create-ecdh@4.0.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "diffie-hellman": "npm:diffie-hellman@5.0.2",
      "inherits": "npm:inherits@2.0.1",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "public-encrypt": "npm:public-encrypt@4.0.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:des.js@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
    },
    "npm:diffie-hellman@5.0.2": {
      "bn.js": "npm:bn.js@4.11.3",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "miller-rabin": "npm:miller-rabin@4.0.0",
      "randombytes": "npm:randombytes@2.0.3",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:elliptic@6.2.5": {
      "bn.js": "npm:bn.js@4.11.3",
      "brorand": "npm:brorand@1.0.5",
      "hash.js": "npm:hash.js@1.0.3",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:evp_bytestokey@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:hash.js@1.0.3": {
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:miller-rabin@4.0.0": {
      "bn.js": "npm:bn.js@4.11.3",
      "brorand": "npm:brorand@1.0.5"
    },
    "npm:ng2-bootstrap@1.0.16": {
      "@angular/common": "npm:@angular/common@2.0.0-rc.1",
      "@angular/compiler": "npm:@angular/compiler@2.0.0-rc.1",
      "@angular/core": "npm:@angular/core@2.0.0-rc.1",
      "@angular/platform-browser": "npm:@angular/platform-browser@2.0.0-rc.1",
      "@angular/platform-browser-dynamic": "npm:@angular/platform-browser-dynamic@2.0.0-rc.1",
      "moment": "npm:moment@2.13.0"
    },
    "npm:os-browserify@0.1.2": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:parse-asn1@5.0.0": {
      "asn1.js": "npm:asn1.js@4.6.0",
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:pbkdf2@3.0.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:process@0.11.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:public-encrypt@4.0.0": {
      "bn.js": "npm:bn.js@4.11.3",
      "browserify-rsa": "npm:browserify-rsa@4.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "randombytes": "npm:randombytes@2.0.3"
    },
    "npm:randombytes@2.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.14": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:ripemd160@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:rxjs@5.0.0-beta.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:sha.js@2.4.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.14"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:typescript@1.8.10": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    },
    "npm:zone.js@0.6.12": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
